spring:
  application:
    name: com.neuraldock

  datasource:
    url: jdbc:mysql://localhost:3306/neuraldock_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true